---
title: "Assignments"
slug: assignments
---


# Homework assignments

[^labinfo]

A homework assignment will be due approximately every three weeks. 

Generally, each assignment covers material we recently covered in class.

They are designed so that you can explore  concepts and tools in more depth.

# Seeking assistance

You should complete the assignments alone, however it is perfectly ok to ask for help. This order is the best for asking for assistance:

1. Start by seeking assistance from sites like [Stackoverflow](https://stackoverflow.com/). Almost every question you can ask has already been answered there.^[The benefit of this approach is that you learn to communicate your issues with other people, and learn to navigate the very considerable amount of web-based informtion available.]

2. Ask the question in a clear manner in a general <i class="fa fa-slack" aria-hidden="true"></i> ${\tt Slack}$ channels  (${\tt \#biol480}$). ^[This allows other students in the class to practice answering  questions. This is where students can earn $+1$s for the quality of their answers.]
   
3. If the question can't be answered by other students on ${\tt Slack}$, either the TA or I can assist via ${\tt Slack}$.^[Note that by always asking questions within ${\tt Slack}$, we have a persistent record of our conversation and the solution.]
   
4. As a very last resort, diret message via ${\tt Slack}$ technical questions to the TA or instructor.^[There are a lot of reasons to avoid DMing us. For example, if we answer a question in a DM, we have to re-answer the next time a student asks the same questions. However, if we answer it in a class-wide channel on ${\tt Slack}$, all students benefit and we only have to write out the answer once.]

We understand that many people are self-conscience when asking questions, and would therefore try to avoid public ${\tt Slack}$ channels. Although there are ways on ${\tt Slack}$ to ask a question anonymously (and you are welcome to use them),  we would prefer that you build towards a pyschology that ***there are no stupid questions***. Learning to communicate with your peers is an important part of your studies.

Remember that you can ask questions during
***labs***, ***TA office hours***, ***instructor office hours*** and ***during the lectures*** (time permitted).


# Submitting assignments

Assignment submission is always electronic and via  <i class="fa fa-google"></i> ${\tt Google Drive}$.

Make sure you have your gmail account and have set the permissions appropriately on google+. Please ensure that it is straightforward for us to associate the name of your gmail account with your real name.^[If the username of your gmail account is e.g. "kingofeverything", it might be hard for us to guess who this, unfortunately.]

Go to  ${\tt Google Drive}$ and create a folder using your last name as the title. 

In this folder, you create a series of subfolders Assignment 1, Assignment 2, Assignment 3, Assignment 4. All files for a particular assignment belong in the associated folder.

After you have put all your files into this directory for the assignment 
(precise formats etc. will be specified in each assignment),
share this folder with 

- ${\bf {\tt biol480.concordia@gmail.com}}$. 

When you share the folder, there is a box that allows you to add a comment. Make sure to add this comment:

- ***BIOL480, Assignment #, Concordia ID, Lastname, Firstname***

# Late assignments

Marginally late work (defined as less than 2 days past the deadline) can be ok, although you are warned that this is usually not the case near mid-terms or  end of term^[This is because it delays us releasing answer keys. Please respect that the TA is working on a tight timeline and any exceptions you ask for blowback of them.]

Late late work (defined as more than 2 days) requires special permission from the instructor. ^[Generally, it is not a problem if it only happens once, the student is proactive in clarifying the situation with the instructor, and it does not hinder us releasing answer keys before midterms and exams.]


[^labinfo]: {-}
  `r blogdown::shortcode("labinfo")`