---
title: "Introduction and orientation"
date: "2020-09-08"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

This is the first class, so allow me to run through how the Readings pages work. 

Both Readings and Video should be completed _before_ the actual lecture. 
The lecture itself is intended for you to ask questions, for me to give out
small quizzes/puzzles/questions (for grades), and for me to provide deeper insight into
the material. 

# Required

- Please read the [Overview](/overview/) for the course.^[Required reading represents fundamental material that you are expected to master. You can be tested on this material.] 

- Please read the Chapter 1 Introduction of the [course textbook](https://r4ds.had.co.nz/introduction.html). Do not worry if you have difficulties understanding the technical details at the end. 


# Recommended

- Wiki provides a nice page with a bit of the history of the field and its objectives [What is Bioinformatics?](https://en.wikipedia.org/wiki/Bioinformatics#:~:text=Historically%2C%20the%20term%20bioinformatics%20did,chemical%20processes%20in%20biological%20systems)).^[I disagree slightly with some of the definitions and terms here. I have slightly different operational definitions of computational biology, bioinformatics and data science. It really doesn't matter.]

- Read a little about the R language [here](https://www.r-project.org/about.html).

- R is a so-called [GNU](https://www.gnu.org/) project. Please read a little about Open Source software [here](https://en.wikipedia.org/wiki/Free_and_open-source_software).



# Action items  

- Obtain your gmail account and send it to us as per the instructions.

- While you are at gmail, check to make sure you are comfortable with your privacy settings.

- Explore Google Drive. Create a Google Doc and transfer it to your local machine. Transfer a text document to Google Drive. Experiment a bit with Google Sheets, Slides, Draw etc.

- Also, read the fine print for ownership and permissions for your data that is stored in the Cloud at Google Drive. Does Google reserve the right to look at your documents? Can they compile [meta-data](https://en.wikipedia.org/wiki/Metadata) from your documents.

- In your brower^[This course was developed using the Chrome browser.  I made an effort to make the content universal regardless of browser. Nevertheless, if you have trouble with web pages or linking to material, you might retry using Chrome.] bookmark some of the main links that you need for the course (course page, textbook link, Zoom room, Slack, etc.). oSlack, Drive, Zoom and some other tools have apps that run on your local machine. This is sometimes more convenient that web-based access.

# Points of reflection

- Create accounts for any of the relevant software we will use (eg Slack, RStudio Cloud). I would recommend consistently using your gmail account. 

- How do you handle passwords? I suspect we are all tired of the chaos across so many sites. Have you designed a private ultra-secure scheme for choosing your passwords so that they are easy to remember yet ultra-secure? 

- Who in the right mind would spend hours and hours of their time developing software and then give it out for free?!?!?! 

